### ISSUE TITLE
Email quick compose - no scrolling

### ISSUE THREAD

**Issue by joshuahilton** [salesagility/SuiteCRM#3545]
#### Issue

When clicking on an email address to bring up the quick compose dialog, there is no scrolling enabled in the dialog so users cannot enter the body for the email message.

Similar to case [#2981](https://github.com/salesagility/SuiteCRM/issues/2981) but this also occurs on a laptop or desktop, not just an iPad.

![capture](https://cloud.githubusercontent.com/assets/26759852/25978107/653b8c4e-3714-11e7-97b7-daeae306518a.PNG)

#### Expected Behavior

Should be able to scroll.

#### Actual Behavior

Scrolling does not work.

#### Possible Fix

remove the yui-layout-noscroll or add overflow:scroll;

#### Steps to Reproduce

1. Click on an email address in contacts or accounts
2. Try scrolling in the quick compose window.
3.
4.

#### Context

On a laptop, desktop and tablet, I am unable to scroll to enter the body message. This impacts on our sales team ability to quickly send emails.

#### Your Environment

* SuiteCRM Version used: Occurs on both 7.8.3 and 7.9 Beta
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 58.0.3029.96 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MYSQL PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Windows 7 Enterprise

**Comment by pgorod** [comment]
@daniel-samson I was going to open a new issue regarding the Beta, but I'm not sure if it's contradictory with this one.

On my 7.9.0 Beta, clicking on links to emails in Contacts and Leads does nothing (does not show the Quick  compose pop-up), and Firefox throws this error:
`onclick: TypeError: $(...).openComposeViewModal is not a function`

It works fine on the online demo of 7.8.3. 

But the bug report above seems to imply that the link works on 7.9.0.beta, and the pop-up opens, the only problem would be the scrolling issue described.

Maybe you've already fixed this in one of the recent commits after the Beta release?

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
